// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20220121202717_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Color")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 4,
                            Breed = "Scottish Fold",
                            Color = "Grey",
                            Gender = "Male",
                            Location = "The Cattery",
                            Name = "Bart",
                            Type = "Cat",
                            Weight = 7.0
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 16,
                            Breed = "Russian Blue",
                            Color = "Grey",
                            Gender = "Male",
                            Location = "The Cattery",
                            Name = "Indy",
                            Type = "Cat",
                            Weight = 8.3000000000000007
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 8,
                            Breed = "American Shorthair",
                            Color = "Black",
                            Gender = "Male",
                            Location = "The Cattery",
                            Name = "Peeve",
                            Type = "Cat",
                            Weight = 6.9000000000000004
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 16,
                            Breed = "American Shorthair",
                            Color = "Tabby",
                            Gender = "Male",
                            Location = "The Cattery",
                            Name = "Buzz",
                            Type = "Cat",
                            Weight = 7.7999999999999998
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 9,
                            Breed = "Maine Coon",
                            Color = "Orange and White",
                            Gender = "Female",
                            Location = "The Cattery",
                            Name = "Lily",
                            Type = "Cat",
                            Weight = 8.8000000000000007
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 5,
                            Breed = "Australian Cattle Dog Mix",
                            Color = "Black and White",
                            Gender = "Male",
                            Location = "The Blue Room",
                            Name = "Pete",
                            Type = "Dog",
                            Weight = 43.0
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 6,
                            Breed = "Hound",
                            Color = "Brown",
                            Gender = "Male",
                            Location = "The Red Room",
                            Name = "Buster",
                            Type = "Dog",
                            Weight = 55.700000000000003
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 4,
                            Breed = "Golden Retriever",
                            Color = "Brown",
                            Gender = "Female",
                            Location = "The Red Room",
                            Name = "Amy",
                            Type = "Dog",
                            Weight = 61.5
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 3,
                            Breed = "Australian Shepherd",
                            Color = "Black and White",
                            Gender = "Female",
                            Location = "The Blue Room",
                            Name = "Lucy",
                            Type = "Dog",
                            Weight = 38.700000000000003
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 8,
                            Breed = "Maltese",
                            Color = "White",
                            Gender = "Female",
                            Location = "The Yellow Room",
                            Name = "Jazz",
                            Type = "Dog",
                            Weight = 15.6
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 9,
                            Breed = "Pomperdoodle",
                            Color = "Black",
                            Gender = "Female",
                            Location = "The Yellow Room",
                            Name = "Xena",
                            Type = "Dog",
                            Weight = 14.800000000000001
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 1,
                            Breed = "Goldendoodle",
                            Color = "Brown",
                            Gender = "Male",
                            Location = "The Red Room",
                            Name = "Oliver",
                            Type = "Dog",
                            Weight = 23.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
